-- Database Schema for QuizNinja API
-- Generated automatically on: 2025-09-27 07:34:55
-- DO NOT EDIT THIS FILE MANUALLY - IT WILL BE OVERWRITTEN
-- Use migrations to modify the database schema

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Functions
CREATE OR REPLACE FUNCTION public.calculate_trending_score(article_id uuid, base_score numeric DEFAULT 50.0)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
DECLARE
    final_score DECIMAL := base_score;
    article_age_hours INTEGER;
    category_boost DECIMAL := 0.0;
    breaking_boost DECIMAL := 0.0;
    hot_boost DECIMAL := 0.0;
    recency_factor DECIMAL := 1.0;
BEGIN
    -- Get article age in hours
    SELECT EXTRACT(EPOCH FROM (NOW() - created_at)) / 3600
    INTO article_age_hours
    FROM digest_articles
    WHERE id = article_id;

    -- Apply recency factor (newer articles get higher scores)
    IF article_age_hours <= 2 THEN
        recency_factor := 2.0;
    ELSIF article_age_hours <= 6 THEN
        recency_factor := 1.5;
    ELSIF article_age_hours <= 12 THEN
        recency_factor := 1.2;
    ELSIF article_age_hours <= 24 THEN
        recency_factor := 1.0;
    ELSE
        recency_factor := 0.8;
    END IF;

    -- Apply category-specific boosts
    SELECT CASE
        WHEN category IN ('Technology', 'Business') THEN 10.0
        WHEN category IN ('Environment', 'Science') THEN 8.0
        WHEN category IN ('Health', 'Politics') THEN 6.0
        ELSE 5.0
    END INTO category_boost
    FROM digest_articles
    WHERE id = article_id;

    -- Apply breaking/hot article boosts
    SELECT
        CASE WHEN is_breaking THEN 20.0 ELSE 0.0 END,
        CASE WHEN is_hot THEN 15.0 ELSE 0.0 END
    INTO breaking_boost, hot_boost
    FROM digest_articles
    WHERE id = article_id;

    -- Calculate final score
    final_score := (base_score + category_boost + breaking_boost + hot_boost) * recency_factor;

    -- Cap the score at 100
    IF final_score > 100.0 THEN
        final_score := 100.0;
    END IF;

    RETURN final_score;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.calculate_user_level(points integer)
 RETURNS character varying
 LANGUAGE plpgsql
AS $function$
BEGIN
    CASE
        WHEN points >= 5000 THEN RETURN 'Master';
        WHEN points >= 3000 THEN RETURN 'Expert';
        WHEN points >= 1500 THEN RETURN 'Advanced';
        WHEN points >= 500 THEN RETURN 'Intermediate';
        ELSE RETURN 'Beginner';
    END CASE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.cleanup_expired_quiz_sessions()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    expired_count INTEGER;
BEGIN
    -- Mark sessions as abandoned if inactive for more than 24 hours
    UPDATE quiz_sessions
    SET session_state = 'abandoned',
        updated_at = CURRENT_TIMESTAMP
    WHERE session_state IN ('active', 'paused')
    AND last_activity_at < CURRENT_TIMESTAMP - INTERVAL '24 hours';

    GET DIAGNOSTICS expired_count = ROW_COUNT;

    -- Also update corresponding quiz attempts
    UPDATE quiz_attempts
    SET status = 'abandoned',
        updated_at = CURRENT_TIMESTAMP
    WHERE id IN (
        SELECT attempt_id FROM quiz_sessions
        WHERE session_state = 'abandoned'
        AND status != 'abandoned'
    );

    RETURN expired_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.cleanup_friendship_on_status_change()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- If a friend request is cancelled or deleted, remove the friendship
    IF (OLD.status = 'accepted' AND NEW.status IN ('cancelled', 'rejected')) OR TG_OP = 'DELETE' THEN
        DELETE FROM friendships
        WHERE (user1_id = LEAST(OLD.requester_id, OLD.requested_id)
               AND user2_id = GREATEST(OLD.requester_id, OLD.requested_id));
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_challenge_notification()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Create notification for new challenge
    IF TG_OP = 'INSERT' THEN
        INSERT INTO friend_notifications (user_id, type, title, message, related_user_id, created_at)
        SELECT
            NEW.challenged_id,
            'challenge_received',
            'New Challenge Received',
            u.name || ' challenged you to a quiz!',
            NEW.challenger_id,
            CURRENT_TIMESTAMP
        FROM users u WHERE u.id = NEW.challenger_id;

        RETURN NEW;
    END IF;

    -- Create notification for challenge status changes
    IF TG_OP = 'UPDATE' THEN
        -- Challenge accepted
        IF NEW.status = 'accepted' AND OLD.status = 'pending' THEN
            INSERT INTO friend_notifications (user_id, type, title, message, related_user_id, created_at)
            SELECT
                NEW.challenger_id,
                'challenge_accepted',
                'Challenge Accepted',
                u.name || ' accepted your challenge!',
                NEW.challenged_id,
                CURRENT_TIMESTAMP
            FROM users u WHERE u.id = NEW.challenged_id;
        END IF;

        -- Challenge declined
        IF NEW.status = 'declined' AND OLD.status = 'pending' THEN
            INSERT INTO friend_notifications (user_id, type, title, message, related_user_id, created_at)
            SELECT
                NEW.challenger_id,
                'challenge_declined',
                'Challenge Declined',
                u.name || ' declined your challenge.',
                NEW.challenged_id,
                CURRENT_TIMESTAMP
            FROM users u WHERE u.id = NEW.challenged_id;
        END IF;

        -- Challenge completed
        IF NEW.status = 'completed' AND OLD.status = 'accepted' THEN
            -- Determine winner and create notifications for both users
            DECLARE
                winner_id UUID;
                winner_name TEXT;
                loser_id UUID;
            BEGIN
                -- Determine winner
                IF NEW.challenger_score > NEW.challenged_score THEN
                    winner_id := NEW.challenger_id;
                    loser_id := NEW.challenged_id;
                ELSIF NEW.challenged_score > NEW.challenger_score THEN
                    winner_id := NEW.challenged_id;
                    loser_id := NEW.challenger_id;
                END IF;

                -- Create completion notification for challenger
                INSERT INTO friend_notifications (user_id, type, title, message, related_user_id, created_at)
                SELECT
                    NEW.challenger_id,
                    'challenge_completed',
                    'Challenge Completed',
                    CASE
                        WHEN NEW.challenger_score > NEW.challenged_score THEN 'You won the challenge against ' || u.name || '!'
                        WHEN NEW.challenger_score < NEW.challenged_score THEN 'You lost the challenge against ' || u.name || '.'
                        ELSE 'Your challenge with ' || u.name || ' ended in a tie!'
                    END,
                    NEW.challenged_id,
                    CURRENT_TIMESTAMP
                FROM users u WHERE u.id = NEW.challenged_id;

                -- Create completion notification for challenged user
                INSERT INTO friend_notifications (user_id, type, title, message, related_user_id, created_at)
                SELECT
                    NEW.challenged_id,
                    'challenge_completed',
                    'Challenge Completed',
                    CASE
                        WHEN NEW.challenged_score > NEW.challenger_score THEN 'You won the challenge against ' || u.name || '!'
                        WHEN NEW.challenged_score < NEW.challenger_score THEN 'You lost the challenge against ' || u.name || '.'
                        ELSE 'Your challenge with ' || u.name || ' ended in a tie!'
                    END,
                    NEW.challenger_id,
                    CURRENT_TIMESTAMP
                FROM users u WHERE u.id = NEW.challenger_id;
            END;
        END IF;

        RETURN NEW;
    END IF;

    RETURN NULL;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_friend_request_notification()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO friend_notifications (user_id, type, title, message, related_user_id, friend_request_id, created_at, is_test_data)
    SELECT
        NEW.requested_id,
        'friend_request',
        'New Friend Request',
        u.name || ' sent you a friend request!',
        NEW.requester_id,
        NEW.id,
        CURRENT_TIMESTAMP,
        true
    FROM users u WHERE u.id = NEW.requester_id;

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_friendship_on_accept()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Only create friendship if status changed to 'accepted'
    IF NEW.status = 'accepted' AND OLD.status != 'accepted' THEN
        -- Ensure user1_id < user2_id for consistent ordering
        INSERT INTO friendships (user1_id, user2_id, created_at, is_test_data)
        VALUES (
            LEAST(NEW.requester_id, NEW.requested_id),
            GREATEST(NEW.requester_id, NEW.requested_id),
            CURRENT_TIMESTAMP,
            true
        )
        ON CONFLICT (user1_id, user2_id) DO NOTHING;

        -- Update responded_at timestamp
        NEW.responded_at = CURRENT_TIMESTAMP;

        -- Create notification for requester
        INSERT INTO friend_notifications (user_id, type, title, message, related_user_id, friend_request_id, created_at, is_test_data)
        SELECT
            NEW.requester_id,
            'friend_accepted',
            'Friend Request Accepted',
            u.name || ' accepted your friend request!',
            NEW.requested_id,
            NEW.id,
            CURRENT_TIMESTAMP,
            true
        FROM users u WHERE u.id = NEW.requested_id;
    END IF;

    -- Create notification for rejection
    IF NEW.status = 'rejected' AND OLD.status != 'rejected' THEN
        NEW.responded_at = CURRENT_TIMESTAMP;

        INSERT INTO friend_notifications (user_id, type, title, message, related_user_id, friend_request_id, created_at, is_test_data)
        SELECT
            NEW.requester_id,
            'friend_rejected',
            'Friend Request Declined',
            u.name || ' declined your friend request.',
            NEW.requested_id,
            NEW.id,
            CURRENT_TIMESTAMP,
            true
        FROM users u WHERE u.id = NEW.requested_id;
    END IF;

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.expire_challenges()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Auto-expire challenges that are past their expiry date
    UPDATE challenges
    SET status = 'expired', updated_at = CURRENT_TIMESTAMP
    WHERE expires_at < CURRENT_TIMESTAMP
    AND status IN ('pending', 'accepted');

    RETURN NULL;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_digest_categories()
 RETURNS TABLE(category character varying)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT DISTINCT da.category
    FROM digest_articles da
    WHERE da.is_dummy = false
    ORDER BY da.category;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_or_create_todays_digest()
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
DECLARE
    digest_id UUID;
BEGIN
    -- Try to find today's digest
    SELECT id INTO digest_id
    FROM digests
    WHERE date = CURRENT_DATE;

    -- If not found, create it
    IF digest_id IS NULL THEN
        INSERT INTO digests (date, title, summary, is_dummy)
        VALUES (
            CURRENT_DATE,
            'Daily News Digest',
            'Stay informed with the most important news from around the world.',
            false
        )
        RETURNING id INTO digest_id;
    END IF;

    RETURN digest_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_challenges_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_digest_article_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE digests
        SET article_count = (
            SELECT COUNT(*)
            FROM digest_articles
            WHERE digest_id = NEW.digest_id
        ),
        updated_at = NOW()
        WHERE id = NEW.digest_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE digests
        SET article_count = (
            SELECT COUNT(*)
            FROM digest_articles
            WHERE digest_id = OLD.digest_id
        ),
        updated_at = NOW()
        WHERE id = OLD.digest_id;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_digest_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_quiz_session_activity()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.last_activity_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_trending_rankings()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    article_record RECORD;
    rank_counter INTEGER := 1;
BEGIN
    -- First, calculate trending scores for all articles
    FOR article_record IN
        SELECT id FROM digest_articles
        WHERE created_at >= NOW() - INTERVAL '7 days' -- Only consider articles from last 7 days
        ORDER BY created_at DESC
    LOOP
        UPDATE digest_articles
        SET trending_score = calculate_trending_score(article_record.id)
        WHERE id = article_record.id;
    END LOOP;

    -- Mark top articles as trending (top 20 by score)
    UPDATE digest_articles SET is_trending = FALSE, trending_rank = NULL;

    FOR article_record IN
        SELECT id FROM digest_articles
        WHERE trending_score > 60.0 -- Minimum score threshold
        AND created_at >= NOW() - INTERVAL '7 days'
        ORDER BY trending_score DESC
        LIMIT 20
    LOOP
        UPDATE digest_articles
        SET is_trending = TRUE, trending_rank = rank_counter
        WHERE id = article_record.id;

        rank_counter := rank_counter + 1;
    END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_leaderboard_stats()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- This function will be called when quiz_attempts are updated/inserted
    -- For now, it's a placeholder for future automatic stat updates
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_level()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Update level based on new total_points
    NEW.level = calculate_user_level(NEW.total_points);
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_preferences_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.uuid_generate_v1()
 RETURNS uuid
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_generate_v1$function$
;

CREATE OR REPLACE FUNCTION public.uuid_generate_v1mc()
 RETURNS uuid
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_generate_v1mc$function$
;

CREATE OR REPLACE FUNCTION public.uuid_generate_v3(namespace uuid, name text)
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_generate_v3$function$
;

CREATE OR REPLACE FUNCTION public.uuid_generate_v4()
 RETURNS uuid
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_generate_v4$function$
;

CREATE OR REPLACE FUNCTION public.uuid_generate_v5(namespace uuid, name text)
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_generate_v5$function$
;

CREATE OR REPLACE FUNCTION public.uuid_nil()
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_nil$function$
;

CREATE OR REPLACE FUNCTION public.uuid_ns_dns()
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_ns_dns$function$
;

CREATE OR REPLACE FUNCTION public.uuid_ns_oid()
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_ns_oid$function$
;

CREATE OR REPLACE FUNCTION public.uuid_ns_url()
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_ns_url$function$
;

CREATE OR REPLACE FUNCTION public.uuid_ns_x500()
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_ns_x500$function$
;

-- Tables
CREATE TABLE achievements (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    key VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    icon VARCHAR(100),
    color VARCHAR(50) DEFAULT '#FFD700'::character varying,
    points_reward INTEGER DEFAULT 0,
    category VARCHAR(50) NOT NULL DEFAULT 'general'::character varying,
    is_rare BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    UNIQUE (key),
    PRIMARY KEY (id)
);
CREATE TABLE app_settings (
    key VARCHAR(100) NOT NULL,
    value TEXT,
    description TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (key)
);
CREATE TABLE challenges (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    challenger_id UUID NOT NULL,
    challenged_id UUID NOT NULL,
    quiz_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending'::character varying,
    challenger_score DECIMAL,
    challenged_score DECIMAL,
    message TEXT,
    expires_at TIMESTAMP,
    is_group_challenge BOOLEAN DEFAULT false,
    participant_ids _UUID,
    participant_scores JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (challenged_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (challenger_id) REFERENCES users(id) ON DELETE CASCADE,
    CHECK ((challenger_id <> challenged_id)),
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'accepted'::character varying, 'completed'::character varying, 'expired'::character varying, 'declined'::character varying])::text[])))
);
CREATE TABLE difficulty_levels (
    id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    icon_name VARCHAR(100),
    background_color_hex VARCHAR(7),
    is_test_data BOOLEAN DEFAULT false,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE TABLE digest_articles (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    digest_id UUID NOT NULL,
    title VARCHAR(500) NOT NULL,
    content TEXT NOT NULL,
    summary TEXT NOT NULL,
    source VARCHAR(255),
    author VARCHAR(255),
    published_at TIMESTAMP WITH TIME ZONE,
    category VARCHAR(100) NOT NULL,
    image_url VARCHAR(500),
    external_url VARCHAR(500),
    read_time_minutes INTEGER,
    is_breaking BOOLEAN DEFAULT false,
    is_hot BOOLEAN DEFAULT false,
    is_dummy BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    is_trending BOOLEAN DEFAULT false,
    trending_score DECIMAL DEFAULT 0.0,
    trending_rank INTEGER,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (digest_id) REFERENCES digests(id) ON DELETE CASCADE,
    PRIMARY KEY (id)
);
CREATE TABLE digests (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT,
    article_count INTEGER DEFAULT 0,
    is_dummy BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    is_test_data BOOLEAN DEFAULT false,
    UNIQUE (date),
    PRIMARY KEY (id)
);
CREATE TABLE discussion_likes (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    discussion_id UUID,
    user_id UUID,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (discussion_id) REFERENCES discussions(id) ON DELETE CASCADE,
    UNIQUE (discussion_id, user_id),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE discussion_replies (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    discussion_id UUID,
    user_id UUID,
    content TEXT NOT NULL,
    likes_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (discussion_id) REFERENCES discussions(id) ON DELETE CASCADE,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE discussion_reply_likes (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    reply_id UUID,
    user_id UUID,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (reply_id) REFERENCES discussion_replies(id) ON DELETE CASCADE,
    UNIQUE (reply_id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE discussions (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    quiz_id UUID,
    question_id UUID,
    user_id UUID,
    content TEXT NOT NULL,
    likes_count INTEGER DEFAULT 0,
    replies_count INTEGER DEFAULT 0,
    type VARCHAR(20) DEFAULT 'general'::character varying,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE friend_notifications (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT,
    related_user_id UUID,
    friend_request_id UUID,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (friend_request_id) REFERENCES friend_requests(id) ON DELETE CASCADE,
    PRIMARY KEY (id),
    FOREIGN KEY (related_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CHECK (((type)::text = ANY ((ARRAY['friend_request'::character varying, 'friend_accepted'::character varying, 'friend_rejected'::character varying, 'challenge_received'::character varying, 'challenge_accepted'::character varying, 'challenge_declined'::character varying, 'challenge_completed'::character varying])::text[]))),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE friend_requests (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    requester_id UUID NOT NULL,
    requested_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending'::character varying,
    message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    CHECK ((requester_id <> requested_id)),
    PRIMARY KEY (id),
    FOREIGN KEY (requested_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (requester_id, requested_id),
    CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'cancelled'::character varying])::text[])))
);
CREATE TABLE friendships (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user1_id UUID NOT NULL,
    user2_id UUID NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    CHECK ((user1_id <> user2_id)),
    CHECK ((user1_id < user2_id)),
    PRIMARY KEY (id),
    FOREIGN KEY (user1_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (user1_id, user2_id),
    FOREIGN KEY (user2_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE interests (
    id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    icon_name VARCHAR(100),
    color_hex VARCHAR(7),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE TABLE leaderboard_snapshots (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    snapshot_date DATE NOT NULL,
    period_type VARCHAR(20) NOT NULL,
    rank_position INTEGER NOT NULL,
    total_points INTEGER NOT NULL,
    quizzes_completed INTEGER NOT NULL,
    average_score DECIMAL NOT NULL,
    current_streak INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (user_id, snapshot_date, period_type)
);
CREATE TABLE notification_frequencies (
    id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    icon_name VARCHAR(100),
    is_test_data BOOLEAN DEFAULT false,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE TABLE questions (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    quiz_id UUID,
    question_text TEXT NOT NULL,
    question_type VARCHAR(50) NOT NULL,
    options TEXT[],
    correct_answer TEXT NOT NULL,
    explanation TEXT,
    order_index INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
);
CREATE TABLE quiz_attempts (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    quiz_id UUID,
    user_id UUID,
    score DECIMAL NOT NULL,
    total_points INTEGER NOT NULL,
    time_spent INTEGER NOT NULL,
    is_completed BOOLEAN DEFAULT false,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    answers JSONB,
    percentage_score DECIMAL,
    passed BOOLEAN DEFAULT false,
    status VARCHAR(20) DEFAULT 'started'::character varying,
    retake_count INTEGER DEFAULT 0,
    original_attempt_id UUID,
    performance_comparison JSONB,
    session_data JSONB,
    is_test_data BOOLEAN DEFAULT false,
    CHECK (((status)::text = ANY ((ARRAY['started'::character varying, 'paused'::character varying, 'completed'::character varying, 'abandoned'::character varying])::text[]))),
    CHECK (((retake_count >= 0) AND (retake_count <= 3))),
    FOREIGN KEY (original_attempt_id) REFERENCES quiz_attempts(id),
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE quiz_ratings (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    quiz_id UUID,
    rating INTEGER,
    review TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    CHECK (((rating >= 1) AND (rating <= 5))),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (user_id, quiz_id)
);
CREATE TABLE quiz_sessions (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    attempt_id UUID NOT NULL,
    user_id UUID NOT NULL,
    quiz_id UUID NOT NULL,
    current_question_index INTEGER NOT NULL DEFAULT 0,
    current_answers JSONB DEFAULT '[]'::jsonb,
    session_state VARCHAR(20) NOT NULL DEFAULT 'active'::character varying,
    time_remaining INTEGER,
    time_spent_so_far INTEGER NOT NULL DEFAULT 0,
    last_activity_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    paused_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (attempt_id) REFERENCES quiz_attempts(id) ON DELETE CASCADE,
    UNIQUE (attempt_id),
    CHECK ((current_question_index >= 0)),
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    CHECK (((session_state)::text = ANY ((ARRAY['active'::character varying, 'paused'::character varying, 'completed'::character varying, 'abandoned'::character varying])::text[]))),
    CHECK (((time_remaining IS NULL) OR (time_remaining >= 0))),
    CHECK ((time_spent_so_far >= 0)),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE quiz_statistics (
    quiz_id UUID NOT NULL,
    total_attempts INTEGER DEFAULT 0,
    total_completions INTEGER DEFAULT 0,
    average_score DECIMAL DEFAULT 0.0,
    average_time_seconds INTEGER DEFAULT 0,
    difficulty_rating DECIMAL DEFAULT 0.0,
    popularity_score INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (quiz_id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
);
CREATE TABLE quizzes (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    title VARCHAR(500) NOT NULL,
    description TEXT,
    category_id VARCHAR(50),
    difficulty VARCHAR(50),
    article_summary TEXT,
    total_questions INTEGER NOT NULL,
    time_limit_minutes INTEGER NOT NULL,
    points INTEGER NOT NULL,
    is_featured BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    is_public BOOLEAN DEFAULT true,
    tags TEXT[] DEFAULT '{}'::text[],
    thumbnail_url VARCHAR(500),
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (category_id) REFERENCES interests(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (difficulty) REFERENCES difficulty_levels(id),
    PRIMARY KEY (id)
);
CREATE TABLE refresh_tokens (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    token VARCHAR(500) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (token),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE user_achievements (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    achievement_id UUID,
    unlocked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    points_awarded INTEGER DEFAULT 0,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (achievement_id) REFERENCES achievements(id) ON DELETE CASCADE,
    PRIMARY KEY (id),
    UNIQUE (user_id, achievement_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE user_category_performance (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    category_id VARCHAR(100) NOT NULL,
    category_name VARCHAR(255) NOT NULL,
    total_points INTEGER DEFAULT 0,
    quizzes_completed INTEGER DEFAULT 0,
    average_score DECIMAL DEFAULT 0.0,
    best_score DECIMAL DEFAULT 0.0,
    last_attempt_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    UNIQUE (user_id, category_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE user_preferences (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    selected_interests TEXT[],
    difficulty_preference VARCHAR(50),
    notifications_enabled BOOLEAN DEFAULT true,
    notification_frequency VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    profile_visibility BOOLEAN DEFAULT true,
    show_online_status BOOLEAN DEFAULT true,
    allow_friend_requests BOOLEAN DEFAULT true,
    share_activity_status BOOLEAN DEFAULT true,
    notification_types JSONB DEFAULT '{"challenges": true, "achievements": true, "quiz_reminders": true, "friend_activity": true, "leaderboard_updates": false, "system_announcements": true}'::jsonb,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    onboarding_completed_at TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE user_quiz_favorites (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    quiz_id UUID,
    favorited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (user_id, quiz_id)
);
CREATE TABLE user_rank_history (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    period_type VARCHAR(20) NOT NULL,
    old_rank INTEGER,
    new_rank INTEGER NOT NULL,
    rank_change INTEGER NOT NULL DEFAULT 0,
    points_at_change INTEGER NOT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE users (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    age INTEGER,
    password_hash VARCHAR(255) NOT NULL,
    level VARCHAR(50) DEFAULT 'Beginner'::character varying,
    total_points INTEGER DEFAULT 0,
    current_streak INTEGER DEFAULT 0,
    best_streak INTEGER DEFAULT 0,
    total_quizzes_completed INTEGER DEFAULT 0,
    average_score DECIMAL DEFAULT 0.0,
    is_online BOOLEAN DEFAULT false,
    last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    avatar_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    UNIQUE (email),
    PRIMARY KEY (id)
);
-- Indexes
CREATE INDEX idx_achievements_is_test_data ON public.achievements USING btree (is_test_data);
CREATE INDEX idx_app_settings_key ON public.app_settings USING btree (key);
CREATE INDEX idx_challenges_challenged_id ON public.challenges USING btree (challenged_id);
CREATE INDEX idx_challenges_challenger_id ON public.challenges USING btree (challenger_id);
CREATE INDEX idx_challenges_created_at ON public.challenges USING btree (created_at);
CREATE INDEX idx_challenges_expires_at ON public.challenges USING btree (expires_at);
CREATE INDEX idx_challenges_is_test_data ON public.challenges USING btree (is_test_data);
CREATE INDEX idx_challenges_quiz_id ON public.challenges USING btree (quiz_id);
CREATE INDEX idx_challenges_status ON public.challenges USING btree (status);
CREATE INDEX idx_difficulty_levels_name ON public.difficulty_levels USING btree (name);
CREATE INDEX idx_digest_articles_category ON public.digest_articles USING btree (category);
CREATE INDEX idx_digest_articles_created_at ON public.digest_articles USING btree (created_at DESC);
CREATE INDEX idx_digest_articles_digest_id ON public.digest_articles USING btree (digest_id);
CREATE INDEX idx_digest_articles_is_breaking ON public.digest_articles USING btree (is_breaking);
CREATE INDEX idx_digest_articles_is_dummy ON public.digest_articles USING btree (is_dummy);
CREATE INDEX idx_digest_articles_is_hot ON public.digest_articles USING btree (is_hot);
CREATE INDEX idx_digest_articles_is_test_data ON public.digest_articles USING btree (is_test_data);
CREATE INDEX idx_digest_articles_is_trending ON public.digest_articles USING btree (is_trending);
CREATE INDEX idx_digest_articles_published_at ON public.digest_articles USING btree (published_at DESC);
CREATE INDEX idx_digest_articles_trending_composite ON public.digest_articles USING btree (is_trending, trending_score DESC, created_at DESC) WHERE (is_trending = true);
CREATE INDEX idx_digest_articles_trending_rank ON public.digest_articles USING btree (trending_rank);
CREATE INDEX idx_digest_articles_trending_score ON public.digest_articles USING btree (trending_score DESC);
CREATE INDEX idx_digests_created_at ON public.digests USING btree (created_at DESC);
CREATE INDEX idx_digests_date ON public.digests USING btree (date DESC);
CREATE INDEX idx_digests_is_dummy ON public.digests USING btree (is_dummy);
CREATE INDEX idx_digests_is_test_data ON public.digests USING btree (is_test_data);
CREATE INDEX idx_discussion_likes_discussion_id ON public.discussion_likes USING btree (discussion_id);
CREATE INDEX idx_discussion_likes_user_id ON public.discussion_likes USING btree (user_id);
CREATE INDEX idx_discussion_replies_created_at ON public.discussion_replies USING btree (created_at);
CREATE INDEX idx_discussion_replies_discussion_id ON public.discussion_replies USING btree (discussion_id);
CREATE INDEX idx_discussion_replies_user_id ON public.discussion_replies USING btree (user_id);
CREATE INDEX idx_discussion_reply_likes_reply_id ON public.discussion_reply_likes USING btree (reply_id);
CREATE INDEX idx_discussion_reply_likes_user_id ON public.discussion_reply_likes USING btree (user_id);
CREATE INDEX idx_discussions_created_at ON public.discussions USING btree (created_at);
CREATE INDEX idx_discussions_is_test_data ON public.discussions USING btree (is_test_data);
CREATE INDEX idx_discussions_question_id ON public.discussions USING btree (question_id);
CREATE INDEX idx_discussions_quiz_id ON public.discussions USING btree (quiz_id);
CREATE INDEX idx_discussions_user_id ON public.discussions USING btree (user_id);
CREATE INDEX idx_friend_notifications_created_at ON public.friend_notifications USING btree (created_at);
CREATE INDEX idx_friend_notifications_is_read ON public.friend_notifications USING btree (is_read);
CREATE INDEX idx_friend_notifications_related_user_id ON public.friend_notifications USING btree (related_user_id);
CREATE INDEX idx_friend_notifications_type ON public.friend_notifications USING btree (type);
CREATE INDEX idx_friend_notifications_user_id ON public.friend_notifications USING btree (user_id);
CREATE INDEX idx_friend_requests_created_at ON public.friend_requests USING btree (created_at);
CREATE INDEX idx_friend_requests_requested_id ON public.friend_requests USING btree (requested_id);
CREATE INDEX idx_friend_requests_requester_id ON public.friend_requests USING btree (requester_id);
CREATE INDEX idx_friend_requests_status ON public.friend_requests USING btree (status);
CREATE INDEX idx_friendships_created_at ON public.friendships USING btree (created_at);
CREATE INDEX idx_friendships_user1_id ON public.friendships USING btree (user1_id);
CREATE INDEX idx_friendships_user2_id ON public.friendships USING btree (user2_id);
CREATE INDEX idx_interests_name ON public.interests USING btree (name);
CREATE INDEX idx_leaderboard_snapshots_date_period ON public.leaderboard_snapshots USING btree (snapshot_date, period_type);
CREATE INDEX idx_leaderboard_snapshots_rank ON public.leaderboard_snapshots USING btree (rank_position);
CREATE INDEX idx_leaderboard_snapshots_user_id ON public.leaderboard_snapshots USING btree (user_id);
CREATE INDEX idx_notification_frequencies_name ON public.notification_frequencies USING btree (name);
CREATE INDEX idx_questions_is_test_data ON public.questions USING btree (is_test_data);
CREATE INDEX idx_questions_order_index ON public.questions USING btree (order_index);
CREATE INDEX idx_questions_question_type ON public.questions USING btree (question_type);
CREATE INDEX idx_questions_quiz_id ON public.questions USING btree (quiz_id);
CREATE INDEX idx_quiz_attempts_completed_at ON public.quiz_attempts USING btree (completed_at);
CREATE INDEX idx_quiz_attempts_is_completed ON public.quiz_attempts USING btree (is_completed);
CREATE INDEX idx_quiz_attempts_is_test_data ON public.quiz_attempts USING btree (is_test_data);
CREATE INDEX idx_quiz_attempts_original_id ON public.quiz_attempts USING btree (original_attempt_id);
CREATE INDEX idx_quiz_attempts_passed ON public.quiz_attempts USING btree (passed);
CREATE INDEX idx_quiz_attempts_quiz_id ON public.quiz_attempts USING btree (quiz_id);
CREATE INDEX idx_quiz_attempts_retake_count ON public.quiz_attempts USING btree (retake_count);
CREATE INDEX idx_quiz_attempts_started_at ON public.quiz_attempts USING btree (started_at);
CREATE INDEX idx_quiz_attempts_status ON public.quiz_attempts USING btree (status);
CREATE INDEX idx_quiz_attempts_user_id ON public.quiz_attempts USING btree (user_id);
CREATE UNIQUE INDEX idx_quiz_attempts_user_quiz_active ON public.quiz_attempts USING btree (user_id, quiz_id) WHERE (is_completed = false);
CREATE INDEX idx_quiz_ratings_created_at ON public.quiz_ratings USING btree (created_at);
CREATE INDEX idx_quiz_ratings_quiz_id ON public.quiz_ratings USING btree (quiz_id);
CREATE INDEX idx_quiz_ratings_rating ON public.quiz_ratings USING btree (rating);
CREATE INDEX idx_quiz_ratings_user_id ON public.quiz_ratings USING btree (user_id);
CREATE INDEX idx_quiz_sessions_attempt_id ON public.quiz_sessions USING btree (attempt_id);
CREATE INDEX idx_quiz_sessions_last_activity ON public.quiz_sessions USING btree (last_activity_at);
CREATE INDEX idx_quiz_sessions_quiz_id ON public.quiz_sessions USING btree (quiz_id);
CREATE INDEX idx_quiz_sessions_state ON public.quiz_sessions USING btree (session_state);
CREATE INDEX idx_quiz_sessions_user_active ON public.quiz_sessions USING btree (user_id, session_state) WHERE ((session_state)::text = ANY ((ARRAY['active'::character varying, 'paused'::character varying])::text[]));
CREATE INDEX idx_quiz_sessions_user_id ON public.quiz_sessions USING btree (user_id);
CREATE INDEX idx_quiz_statistics_average_score ON public.quiz_statistics USING btree (average_score);
CREATE INDEX idx_quiz_statistics_popularity_score ON public.quiz_statistics USING btree (popularity_score);
CREATE INDEX idx_quiz_statistics_total_attempts ON public.quiz_statistics USING btree (total_attempts);
CREATE INDEX idx_quizzes_category_id ON public.quizzes USING btree (category_id);
CREATE INDEX idx_quizzes_created_at ON public.quizzes USING btree (created_at);
CREATE INDEX idx_quizzes_created_by ON public.quizzes USING btree (created_by);
CREATE INDEX idx_quizzes_difficulty ON public.quizzes USING btree (difficulty);
CREATE INDEX idx_quizzes_is_active ON public.quizzes USING btree (is_active);
CREATE INDEX idx_quizzes_is_featured ON public.quizzes USING btree (is_featured);
CREATE INDEX idx_quizzes_is_public ON public.quizzes USING btree (is_public);
CREATE INDEX idx_quizzes_is_test_data ON public.quizzes USING btree (is_test_data);
CREATE INDEX idx_quizzes_thumbnail_url ON public.quizzes USING btree (thumbnail_url);
CREATE INDEX idx_refresh_tokens_expires_at ON public.refresh_tokens USING btree (expires_at);
CREATE INDEX idx_refresh_tokens_token ON public.refresh_tokens USING btree (token);
CREATE INDEX idx_refresh_tokens_user_id ON public.refresh_tokens USING btree (user_id);
CREATE INDEX idx_user_achievements_achievement_id ON public.user_achievements USING btree (achievement_id);
CREATE INDEX idx_user_achievements_unlocked_at ON public.user_achievements USING btree (unlocked_at);
CREATE INDEX idx_user_achievements_user_id ON public.user_achievements USING btree (user_id);
CREATE INDEX idx_user_category_performance_category_id ON public.user_category_performance USING btree (category_id);
CREATE INDEX idx_user_category_performance_total_points ON public.user_category_performance USING btree (total_points DESC);
CREATE INDEX idx_user_category_performance_user_id ON public.user_category_performance USING btree (user_id);
CREATE INDEX idx_user_preferences_onboarding_completed ON public.user_preferences USING btree (onboarding_completed_at);
CREATE INDEX idx_user_preferences_pending_onboarding ON public.user_preferences USING btree (user_id) WHERE (onboarding_completed_at IS NULL);
CREATE INDEX idx_user_preferences_updated_at ON public.user_preferences USING btree (updated_at);
CREATE INDEX idx_user_preferences_user_id ON public.user_preferences USING btree (user_id);
CREATE INDEX idx_user_quiz_favorites_favorited_at ON public.user_quiz_favorites USING btree (favorited_at);
CREATE INDEX idx_user_quiz_favorites_quiz_id ON public.user_quiz_favorites USING btree (quiz_id);
CREATE INDEX idx_user_quiz_favorites_user_id ON public.user_quiz_favorites USING btree (user_id);
CREATE INDEX idx_user_rank_history_changed_at ON public.user_rank_history USING btree (changed_at);
CREATE INDEX idx_user_rank_history_period ON public.user_rank_history USING btree (period_type);
CREATE INDEX idx_user_rank_history_user_id ON public.user_rank_history USING btree (user_id);
CREATE INDEX idx_users_average_score ON public.users USING btree (average_score DESC);
CREATE INDEX idx_users_current_streak ON public.users USING btree (current_streak DESC);
CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_is_online ON public.users USING btree (is_online);
CREATE INDEX idx_users_is_test_data ON public.users USING btree (is_test_data);
CREATE INDEX idx_users_last_active ON public.users USING btree (last_active);
CREATE INDEX idx_users_level ON public.users USING btree (level);
CREATE INDEX idx_users_total_points ON public.users USING btree (total_points DESC);
CREATE INDEX idx_users_total_quizzes_completed ON public.users USING btree (total_quizzes_completed DESC);
-- Triggers
CREATE TRIGGER trigger_cleanup_friendship_on_status_change BEFORE DELETE OR UPDATE ON public.friend_requests FOR EACH ROW EXECUTE FUNCTION cleanup_friendship_on_status_change();
CREATE TRIGGER trigger_create_challenge_notification AFTER INSERT OR UPDATE ON public.challenges FOR EACH ROW EXECUTE FUNCTION create_challenge_notification();
CREATE TRIGGER trigger_create_friend_request_notification AFTER INSERT ON public.friend_requests FOR EACH ROW EXECUTE FUNCTION create_friend_request_notification();
CREATE TRIGGER trigger_create_friendship_on_accept BEFORE UPDATE ON public.friend_requests FOR EACH ROW EXECUTE FUNCTION create_friendship_on_accept();
CREATE TRIGGER trigger_update_challenges_updated_at BEFORE UPDATE ON public.challenges FOR EACH ROW EXECUTE FUNCTION update_challenges_updated_at();
CREATE TRIGGER trigger_update_digest_article_count_delete AFTER DELETE ON public.digest_articles FOR EACH ROW EXECUTE FUNCTION update_digest_article_count();
CREATE TRIGGER trigger_update_digest_article_count_insert AFTER INSERT ON public.digest_articles FOR EACH ROW EXECUTE FUNCTION update_digest_article_count();
CREATE TRIGGER trigger_update_digests_updated_at BEFORE UPDATE ON public.digests FOR EACH ROW EXECUTE FUNCTION update_digest_updated_at_column();
CREATE TRIGGER trigger_update_user_preferences_updated_at BEFORE UPDATE ON public.user_preferences FOR EACH ROW EXECUTE FUNCTION update_user_preferences_updated_at();
CREATE TRIGGER update_achievements_updated_at BEFORE UPDATE ON public.achievements FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_app_settings_updated_at BEFORE UPDATE ON public.app_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_difficulty_levels_updated_at BEFORE UPDATE ON public.difficulty_levels FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_discussion_replies_updated_at BEFORE UPDATE ON public.discussion_replies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_discussions_updated_at BEFORE UPDATE ON public.discussions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_interests_updated_at BEFORE UPDATE ON public.interests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_notification_frequencies_updated_at BEFORE UPDATE ON public.notification_frequencies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_quiz_attempts_updated_at BEFORE UPDATE ON public.quiz_attempts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_quiz_session_activity_trigger BEFORE UPDATE ON public.quiz_sessions FOR EACH ROW EXECUTE FUNCTION update_quiz_session_activity();
CREATE TRIGGER update_quiz_sessions_updated_at BEFORE UPDATE ON public.quiz_sessions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_quiz_statistics_last_updated BEFORE UPDATE ON public.quiz_statistics FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_quizzes_updated_at BEFORE UPDATE ON public.quizzes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_user_category_performance_updated_at BEFORE UPDATE ON public.user_category_performance FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_users_level_on_points_change BEFORE UPDATE OF total_points ON public.users FOR EACH ROW WHEN ((old.total_points IS DISTINCT FROM new.total_points)) EXECUTE FUNCTION update_user_level();
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
