-- Database Schema for QuizNinja API
-- Generated automatically on: 2025-11-01 17:49:42
-- DO NOT EDIT THIS FILE MANUALLY - IT WILL BE OVERWRITTEN
-- Use migrations to modify the database schema

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pg_graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "supabase_vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Functions
CREATE OR REPLACE FUNCTION public.calculate_trending_score(article_id uuid, base_score numeric DEFAULT 50.0)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
DECLARE
    final_score DECIMAL := base_score;
    article_age_hours INTEGER;
    category_boost DECIMAL := 0.0;
    breaking_boost DECIMAL := 0.0;
    hot_boost DECIMAL := 0.0;
    recency_factor DECIMAL := 1.0;
BEGIN
    -- Get article age in hours
    SELECT EXTRACT(EPOCH FROM (NOW() - created_at)) / 3600
    INTO article_age_hours
    FROM digest_articles
    WHERE id = article_id;

    -- Apply recency factor (newer articles get higher scores)
    IF article_age_hours <= 2 THEN
        recency_factor := 2.0;
    ELSIF article_age_hours <= 6 THEN
        recency_factor := 1.5;
    ELSIF article_age_hours <= 12 THEN
        recency_factor := 1.2;
    ELSIF article_age_hours <= 24 THEN
        recency_factor := 1.0;
    ELSE
        recency_factor := 0.8;
    END IF;

    -- Apply category-specific boosts
    SELECT CASE
        WHEN category IN ('Technology', 'Business') THEN 10.0
        WHEN category IN ('Environment', 'Science') THEN 8.0
        WHEN category IN ('Health', 'Politics') THEN 6.0
        ELSE 5.0
    END INTO category_boost
    FROM digest_articles
    WHERE id = article_id;

    -- Apply breaking/hot article boosts
    SELECT
        CASE WHEN is_breaking THEN 20.0 ELSE 0.0 END,
        CASE WHEN is_hot THEN 15.0 ELSE 0.0 END
    INTO breaking_boost, hot_boost
    FROM digest_articles
    WHERE id = article_id;

    -- Calculate final score
    final_score := (base_score + category_boost + breaking_boost + hot_boost) * recency_factor;

    -- Cap the score at 100
    IF final_score > 100.0 THEN
        final_score := 100.0;
    END IF;

    RETURN final_score;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.calculate_user_level(points integer)
 RETURNS character varying
 LANGUAGE plpgsql
AS $function$
BEGIN
    CASE
        WHEN points >= 5000 THEN RETURN 'Master';
        WHEN points >= 3000 THEN RETURN 'Expert';
        WHEN points >= 1500 THEN RETURN 'Advanced';
        WHEN points >= 500 THEN RETURN 'Intermediate';
        ELSE RETURN 'Beginner';
    END CASE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.cleanup_expired_quiz_sessions()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    cleaned_count INTEGER;
BEGIN
    -- Only clean up completed sessions older than 30 days to free up space
    -- Active and paused sessions are preserved indefinitely to allow resume
    DELETE FROM quiz_sessions
    WHERE session_state = 'completed'
    AND updated_at < CURRENT_TIMESTAMP - INTERVAL '30 days';

    GET DIAGNOSTICS cleaned_count = ROW_COUNT;

    RETURN cleaned_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.cleanup_friendship_on_status_change()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- If a friend request is cancelled or deleted, remove the friendship
    IF (OLD.status = 'accepted' AND NEW.status IN ('cancelled', 'rejected')) OR TG_OP = 'DELETE' THEN
        DELETE FROM friendships
        WHERE (user1_id = LEAST(OLD.requester_id, OLD.requested_id)
               AND user2_id = GREATEST(OLD.requester_id, OLD.requested_id));
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.cleanup_old_deleted_notifications(p_days_old integer DEFAULT 30)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM notifications
    WHERE is_deleted = TRUE
      AND deleted_at < (CURRENT_TIMESTAMP - INTERVAL '1 day' * p_days_old);

    GET DIAGNOSTICS deleted_count = ROW_COUNT;

    RETURN deleted_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_achievement_notification(p_user_id uuid, p_achievement_id uuid, p_achievement_key character varying, p_achievement_title character varying, p_achievement_description text, p_points_awarded integer)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
DECLARE
    notification_id UUID;
BEGIN
    INSERT INTO notifications (
        user_id,
        type,
        title,
        message,
        related_entity_id,
        related_entity_type,
        data,
        created_at
    )
    VALUES (
        p_user_id,
        'achievement_unlocked',
        'Achievement Unlocked!',
        'You unlocked: ' || p_achievement_title,
        p_achievement_id,
        'achievement',
        jsonb_build_object(
            'achievement_id', p_achievement_id,
            'achievement_key', p_achievement_key,
            'achievement_title', p_achievement_title,
            'achievement_description', p_achievement_description,
            'points_awarded', p_points_awarded
        ),
        CURRENT_TIMESTAMP
    )
    RETURNING id INTO notification_id;

    RETURN notification_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_challenge_notification()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Create notification for new challenge
    IF TG_OP = 'INSERT' THEN
        INSERT INTO notifications (user_id, type, title, message, related_user_id, related_entity_id, related_entity_type, data, created_at)
        SELECT
            NEW.challengee_id,
            'challenge_received',
            'New Challenge Received',
            u.name || ' challenged you to a quiz!',
            NEW.challenger_id,
            NEW.id,
            'challenge',
            jsonb_build_object(
                'challenge_id', NEW.id,
                'challenger_name', u.name,
                'quiz_id', NEW.quiz_id,
                'message', NEW.message,
                'expires_at', NEW.expires_at
            ),
            CURRENT_TIMESTAMP
        FROM users u WHERE u.id = NEW.challenger_id;

        RETURN NEW;
    END IF;

    -- Create notification for challenge status changes
    IF TG_OP = 'UPDATE' THEN
        -- Challenge accepted
        IF NEW.status = 'accepted' AND OLD.status = 'pending' THEN
            INSERT INTO notifications (user_id, type, title, message, related_user_id, related_entity_id, related_entity_type, data, created_at)
            SELECT
                NEW.challenger_id,
                'challenge_accepted',
                'Challenge Accepted',
                u.name || ' accepted your challenge!',
                NEW.challengee_id,
                NEW.id,
                'challenge',
                jsonb_build_object(
                    'challenge_id', NEW.id,
                    'accepter_name', u.name,
                    'quiz_id', NEW.quiz_id
                ),
                CURRENT_TIMESTAMP
            FROM users u WHERE u.id = NEW.challengee_id;
        END IF;

        -- Challenge declined
        IF NEW.status = 'declined' AND OLD.status = 'pending' THEN
            INSERT INTO notifications (user_id, type, title, message, related_user_id, related_entity_id, related_entity_type, data, created_at)
            SELECT
                NEW.challenger_id,
                'challenge_declined',
                'Challenge Declined',
                u.name || ' declined your challenge.',
                NEW.challengee_id,
                NEW.id,
                'challenge',
                jsonb_build_object(
                    'challenge_id', NEW.id,
                    'decliner_name', u.name,
                    'quiz_id', NEW.quiz_id
                ),
                CURRENT_TIMESTAMP
            FROM users u WHERE u.id = NEW.challengee_id;
        END IF;

        -- Challenger completed (notify challengee)
        IF NEW.status = 'challenger_completed' AND OLD.status = 'accepted' THEN
            INSERT INTO notifications (user_id, type, title, message, related_user_id, related_entity_id, related_entity_type, data, created_at)
            SELECT
                NEW.challengee_id,
                'challenge_progress',
                'Opponent Completed Quiz',
                u.name || ' completed the challenge quiz. Your turn!',
                NEW.challenger_id,
                NEW.id,
                'challenge',
                jsonb_build_object(
                    'challenge_id', NEW.id,
                    'opponent_name', u.name,
                    'quiz_id', NEW.quiz_id
                ),
                CURRENT_TIMESTAMP
            FROM users u WHERE u.id = NEW.challenger_id;
        END IF;

        -- Challengee completed (notify challenger)
        IF NEW.status = 'challengee_completed' AND OLD.status = 'accepted' THEN
            INSERT INTO notifications (user_id, type, title, message, related_user_id, related_entity_id, related_entity_type, data, created_at)
            SELECT
                NEW.challenger_id,
                'challenge_progress',
                'Opponent Completed Quiz',
                u.name || ' completed the challenge quiz. Your turn!',
                NEW.challengee_id,
                NEW.id,
                'challenge',
                jsonb_build_object(
                    'challenge_id', NEW.id,
                    'opponent_name', u.name,
                    'quiz_id', NEW.quiz_id
                ),
                CURRENT_TIMESTAMP
            FROM users u WHERE u.id = NEW.challengee_id;
        END IF;

        -- Challenge completed (both finished) - determine winner and notify both
        IF NEW.status = 'completed' AND OLD.status IN ('challenger_completed', 'challengee_completed') THEN
            -- Create completion notification for challenger
            INSERT INTO notifications (user_id, type, title, message, related_user_id, related_entity_id, related_entity_type, data, created_at)
            SELECT
                NEW.challenger_id,
                'challenge_completed',
                'Challenge Completed',
                CASE
                    WHEN NEW.challenger_score > NEW.challengee_score THEN 'You won the challenge against ' || u.name || '!'
                    WHEN NEW.challenger_score < NEW.challengee_score THEN 'You lost the challenge against ' || u.name || '.'
                    ELSE 'Your challenge with ' || u.name || ' ended in a tie!'
                END,
                NEW.challengee_id,
                NEW.id,
                'challenge',
                jsonb_build_object(
                    'challenge_id', NEW.id,
                    'opponent_name', u.name,
                    'quiz_id', NEW.quiz_id,
                    'your_score', NEW.challenger_score,
                    'opponent_score', NEW.challengee_score,
                    'result', CASE
                        WHEN NEW.challenger_score > NEW.challengee_score THEN 'won'
                        WHEN NEW.challenger_score < NEW.challengee_score THEN 'lost'
                        ELSE 'tie'
                    END
                ),
                CURRENT_TIMESTAMP
            FROM users u WHERE u.id = NEW.challengee_id;

            -- Create completion notification for challengee
            INSERT INTO notifications (user_id, type, title, message, related_user_id, related_entity_id, related_entity_type, data, created_at)
            SELECT
                NEW.challengee_id,
                'challenge_completed',
                'Challenge Completed',
                CASE
                    WHEN NEW.challengee_score > NEW.challenger_score THEN 'You won the challenge against ' || u.name || '!'
                    WHEN NEW.challengee_score < NEW.challenger_score THEN 'You lost the challenge against ' || u.name || '.'
                    ELSE 'Your challenge with ' || u.name || ' ended in a tie!'
                END,
                NEW.challenger_id,
                NEW.id,
                'challenge',
                jsonb_build_object(
                    'challenge_id', NEW.id,
                    'opponent_name', u.name,
                    'quiz_id', NEW.quiz_id,
                    'your_score', NEW.challengee_score,
                    'opponent_score', NEW.challenger_score,
                    'result', CASE
                        WHEN NEW.challengee_score > NEW.challenger_score THEN 'won'
                        WHEN NEW.challengee_score < NEW.challenger_score THEN 'lost'
                        ELSE 'tie'
                    END
                ),
                CURRENT_TIMESTAMP
            FROM users u WHERE u.id = NEW.challenger_id;
        END IF;

        RETURN NEW;
    END IF;

    RETURN NULL;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_friend_request_notification()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO notifications (user_id, type, title, message, related_user_id, related_entity_id, related_entity_type, data, created_at)
    SELECT
        NEW.requested_id,
        'friend_request',
        'New Friend Request',
        u.name || ' sent you a friend request!',
        NEW.requester_id,
        NEW.id,
        'friend_request',
        jsonb_build_object(
            'friend_request_id', NEW.id,
            'requester_name', u.name,
            'message', NEW.message
        ),
        CURRENT_TIMESTAMP
    FROM users u WHERE u.id = NEW.requester_id;

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_friendship_on_accept()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Only create friendship if status changed to 'accepted'
    IF NEW.status = 'accepted' AND OLD.status != 'accepted' THEN
        -- Ensure user1_id < user2_id for consistent ordering
        INSERT INTO friendships (user1_id, user2_id, created_at)
        VALUES (
            LEAST(NEW.requester_id, NEW.requested_id),
            GREATEST(NEW.requester_id, NEW.requested_id),
            CURRENT_TIMESTAMP
        )
        ON CONFLICT (user1_id, user2_id) DO NOTHING;

        -- Update responded_at timestamp
        NEW.responded_at = CURRENT_TIMESTAMP;

        -- Create notification for requester
        INSERT INTO notifications (user_id, type, title, message, related_user_id, related_entity_id, related_entity_type, data, created_at)
        SELECT
            NEW.requester_id,
            'friend_accepted',
            'Friend Request Accepted',
            u.name || ' accepted your friend request!',
            NEW.requested_id,
            NEW.id,
            'friend_request',
            jsonb_build_object(
                'friend_request_id', NEW.id,
                'accepter_name', u.name
            ),
            CURRENT_TIMESTAMP
        FROM users u WHERE u.id = NEW.requested_id;
    END IF;

    -- Create notification for rejection
    IF NEW.status = 'rejected' AND OLD.status != 'rejected' THEN
        NEW.responded_at = CURRENT_TIMESTAMP;

        INSERT INTO notifications (user_id, type, title, message, related_user_id, related_entity_id, related_entity_type, data, created_at)
        SELECT
            NEW.requester_id,
            'friend_rejected',
            'Friend Request Declined',
            u.name || ' declined your friend request.',
            NEW.requested_id,
            NEW.id,
            'friend_request',
            jsonb_build_object(
                'friend_request_id', NEW.id,
                'decliner_name', u.name
            ),
            CURRENT_TIMESTAMP
        FROM users u WHERE u.id = NEW.requested_id;
    END IF;

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.expire_challenges()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Auto-expire challenges that are past their expiry date
    UPDATE challenges
    SET status = 'expired', updated_at = CURRENT_TIMESTAMP
    WHERE expires_at < CURRENT_TIMESTAMP
    AND status IN ('pending', 'accepted');

    RETURN NULL;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_by_supabase_id(p_supabase_id uuid)
 RETURNS TABLE(id uuid, email character varying, name character varying, auth_method character varying, created_at timestamp without time zone, updated_at timestamp without time zone)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        u.id,
        u.email,
        u.name,
        u.auth_method,
        u.created_at,
        u.updated_at
    FROM users u
    WHERE u.supabase_id = p_supabase_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.migrate_user_to_jwt(p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE
    affected_rows INTEGER;
BEGIN
    UPDATE users
    SET
        auth_method = 'jwt',
        supabase_id = NULL,
        last_auth_method = 'jwt',
        migrated_at = CURRENT_TIMESTAMP
    WHERE id = p_user_id;

    GET DIAGNOSTICS affected_rows = ROW_COUNT;

    IF affected_rows > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.migrate_user_to_supabase(p_user_id uuid, p_supabase_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE
    affected_rows INTEGER;
BEGIN
    -- Check if supabase_id is already in use
    IF EXISTS (SELECT 1 FROM users WHERE supabase_id = p_supabase_id) THEN
        RAISE EXCEPTION 'Supabase ID already linked to another user';
    END IF;

    UPDATE users
    SET
        auth_method = 'supabase',
        supabase_id = p_supabase_id,
        last_auth_method = 'supabase',
        migrated_at = CURRENT_TIMESTAMP
    WHERE id = p_user_id;

    GET DIAGNOSTICS affected_rows = ROW_COUNT;

    IF affected_rows > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.restore_notification(p_notification_id uuid, p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE
    affected_rows INTEGER;
BEGIN
    UPDATE notifications
    SET is_deleted = FALSE, deleted_at = NULL
    WHERE id = p_notification_id
      AND user_id = p_user_id
      AND is_deleted = TRUE;

    GET DIAGNOSTICS affected_rows = ROW_COUNT;

    IF affected_rows > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.soft_delete_notification(p_notification_id uuid, p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE
    affected_rows INTEGER;
BEGIN
    UPDATE notifications
    SET is_deleted = TRUE, deleted_at = CURRENT_TIMESTAMP
    WHERE id = p_notification_id
      AND user_id = p_user_id
      AND is_deleted = FALSE;

    GET DIAGNOSTICS affected_rows = ROW_COUNT;

    IF affected_rows > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_challenges_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_last_active_on_auth()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Only update if last_auth_method actually changed
    IF OLD.last_auth_method IS DISTINCT FROM NEW.last_auth_method THEN
        NEW.last_active = CURRENT_TIMESTAMP;
        NEW.updated_at = CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_notifications_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- This function is prepared for future use if we add updated_at column
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_quiz_session_activity()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.last_activity_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_last_auth_method(p_user_id uuid, p_auth_method character varying)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE
    affected_rows INTEGER;
BEGIN
    -- Validate auth method
    IF p_auth_method NOT IN ('jwt', 'supabase') THEN
        RAISE EXCEPTION 'Invalid auth method: %. Must be jwt or supabase', p_auth_method;
    END IF;

    UPDATE users
    SET
        last_auth_method = p_auth_method,
        updated_at = CURRENT_TIMESTAMP
    WHERE id = p_user_id;

    GET DIAGNOSTICS affected_rows = ROW_COUNT;

    IF affected_rows > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_leaderboard_stats()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- This function will be called when quiz_attempts are updated/inserted
    -- For now, it's a placeholder for future automatic stat updates
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_level()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Update level based on new total_points
    NEW.level = calculate_user_level(NEW.total_points);
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_preferences_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

-- Tables
CREATE TABLE achievements (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    key VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    icon VARCHAR(100),
    color VARCHAR(50) DEFAULT '#FFD700'::character varying,
    points_reward INTEGER DEFAULT 0,
    category VARCHAR(50) NOT NULL DEFAULT 'general'::character varying,
    is_rare BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    UNIQUE (key),
    PRIMARY KEY (id)
);
CREATE TABLE app_settings (
    key VARCHAR(100) NOT NULL,
    value TEXT,
    description TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (key)
);
CREATE TABLE categories (
    id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    icon_name VARCHAR(100),
    color_hex VARCHAR(7),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE TABLE challenges (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    challenger_id UUID NOT NULL,
    challengee_id UUID NOT NULL,
    quiz_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending'::character varying,
    challenger_score DECIMAL,
    challengee_score DECIMAL,
    message TEXT,
    expires_at TIMESTAMP,
    is_group_challenge BOOLEAN DEFAULT false,
    participant_ids _UUID,
    participant_scores JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    challenger_attempt_id UUID,
    challengee_attempt_id UUID,
    challenger_completed_at TIMESTAMP,
    challengee_completed_at TIMESTAMP,
    FOREIGN KEY (challengee_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (challenger_id) REFERENCES users(id) ON DELETE CASCADE,
    CHECK ((challenger_id <> challengee_id)),
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'accepted'::character varying, 'challenger_completed'::character varying, 'challengee_completed'::character varying, 'completed'::character varying, 'expired'::character varying, 'declined'::character varying])::text[]))),
    FOREIGN KEY (challengee_attempt_id) REFERENCES quiz_attempts(id) ON DELETE SET NULL,
    FOREIGN KEY (challenger_attempt_id) REFERENCES quiz_attempts(id) ON DELETE SET NULL
);
CREATE TABLE difficulty_levels (
    id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    icon_name VARCHAR(100),
    background_color_hex VARCHAR(7),
    is_test_data BOOLEAN DEFAULT false,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE TABLE discussion_likes (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    discussion_id UUID,
    user_id UUID,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (discussion_id) REFERENCES discussions(id) ON DELETE CASCADE,
    UNIQUE (discussion_id, user_id),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE discussion_replies (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    discussion_id UUID,
    user_id UUID,
    content TEXT NOT NULL,
    likes_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (discussion_id) REFERENCES discussions(id) ON DELETE CASCADE,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE discussion_reply_likes (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    reply_id UUID,
    user_id UUID,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (reply_id) REFERENCES discussion_replies(id) ON DELETE CASCADE,
    UNIQUE (reply_id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE discussions (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    quiz_id UUID,
    question_id UUID,
    user_id UUID,
    content TEXT NOT NULL,
    likes_count INTEGER DEFAULT 0,
    replies_count INTEGER DEFAULT 0,
    type VARCHAR(20) DEFAULT 'general'::character varying,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE friend_requests (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    requester_id UUID NOT NULL,
    requested_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending'::character varying,
    message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    CHECK ((requester_id <> requested_id)),
    PRIMARY KEY (id),
    FOREIGN KEY (requested_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (requester_id, requested_id),
    CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'cancelled'::character varying])::text[])))
);
CREATE TABLE friendships (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user1_id UUID NOT NULL,
    user2_id UUID NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    CHECK ((user1_id <> user2_id)),
    CHECK ((user1_id < user2_id)),
    PRIMARY KEY (id),
    FOREIGN KEY (user1_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (user1_id, user2_id),
    FOREIGN KEY (user2_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE leaderboard_snapshots (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    snapshot_date DATE NOT NULL,
    period_type VARCHAR(20) NOT NULL,
    rank_position INTEGER NOT NULL,
    total_points INTEGER NOT NULL,
    quizzes_completed INTEGER NOT NULL,
    average_score DECIMAL NOT NULL,
    current_streak INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (user_id, snapshot_date, period_type)
);
CREATE TABLE notification_frequencies (
    id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    icon_name VARCHAR(100),
    is_test_data BOOLEAN DEFAULT false,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE TABLE notifications (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT,
    data JSONB DEFAULT '{}'::jsonb,
    related_user_id UUID,
    related_entity_id UUID,
    related_entity_type VARCHAR(50),
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP,
    expires_at TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMP,
    CHECK ((((is_deleted = false) AND (deleted_at IS NULL)) OR ((is_deleted = true) AND (deleted_at IS NOT NULL)))),
    PRIMARY KEY (id),
    FOREIGN KEY (related_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CHECK (((type)::text = ANY ((ARRAY['friend_request'::character varying, 'friend_accepted'::character varying, 'friend_rejected'::character varying, 'challenge_received'::character varying, 'challenge_accepted'::character varying, 'challenge_declined'::character varying, 'challenge_progress'::character varying, 'challenge_completed'::character varying, 'achievement_unlocked'::character varying, 'general'::character varying, 'system_announcement'::character varying])::text[]))),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE questions (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    quiz_id UUID,
    question_text TEXT NOT NULL,
    question_type VARCHAR(50) NOT NULL,
    options TEXT[],
    correct_answer TEXT NOT NULL,
    explanation TEXT,
    order_index INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
);
CREATE TABLE quiz_attempts (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    quiz_id UUID,
    user_id UUID,
    score DECIMAL NOT NULL,
    total_points INTEGER NOT NULL,
    time_spent INTEGER NOT NULL,
    is_completed BOOLEAN DEFAULT false,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    answers JSONB,
    percentage_score DECIMAL,
    passed BOOLEAN DEFAULT false,
    status VARCHAR(20) DEFAULT 'started'::character varying,
    session_data JSONB,
    is_test_data BOOLEAN DEFAULT false,
    challenge_id UUID,
    is_challenge_attempt BOOLEAN DEFAULT false,
    CHECK (((is_completed = false) OR ((is_completed = true) AND (percentage_score IS NOT NULL)))),
    CHECK (((is_completed = false) OR ((is_completed = true) AND ((status)::text = 'completed'::text)))),
    CHECK (((is_completed = false) OR ((is_completed = true) AND (completed_at IS NOT NULL)))),
    CHECK (((percentage_score IS NULL) OR ((percentage_score < (60)::numeric) AND (passed = false)) OR ((percentage_score >= (60)::numeric) AND (passed = true)))),
    CHECK (((status)::text = ANY ((ARRAY['started'::character varying, 'paused'::character varying, 'completed'::character varying, 'abandoned'::character varying])::text[]))),
    FOREIGN KEY (challenge_id) REFERENCES challenges(id) ON DELETE SET NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE quiz_ratings (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    quiz_id UUID,
    rating INTEGER,
    review TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    CHECK (((rating >= 1) AND (rating <= 5))),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (user_id, quiz_id)
);
CREATE TABLE quiz_sessions (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    attempt_id UUID NOT NULL,
    user_id UUID NOT NULL,
    quiz_id UUID NOT NULL,
    current_question_index INTEGER NOT NULL DEFAULT 0,
    current_answers JSONB DEFAULT '[]'::jsonb,
    session_state VARCHAR(20) NOT NULL DEFAULT 'active'::character varying,
    time_remaining INTEGER,
    time_spent_so_far INTEGER NOT NULL DEFAULT 0,
    last_activity_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    paused_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (attempt_id) REFERENCES quiz_attempts(id) ON DELETE CASCADE,
    UNIQUE (attempt_id),
    CHECK ((current_question_index >= 0)),
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    CHECK (((session_state)::text = ANY ((ARRAY['active'::character varying, 'paused'::character varying, 'completed'::character varying, 'abandoned'::character varying])::text[]))),
    CHECK (((time_remaining IS NULL) OR (time_remaining >= 0))),
    CHECK ((time_spent_so_far >= 0)),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE quiz_statistics (
    quiz_id UUID NOT NULL,
    total_attempts INTEGER DEFAULT 0,
    total_completions INTEGER DEFAULT 0,
    average_score DECIMAL DEFAULT 0.0,
    average_time_seconds INTEGER DEFAULT 0,
    difficulty_rating DECIMAL DEFAULT 0.0,
    popularity_score INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (quiz_id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
);
CREATE TABLE quizzes (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    title VARCHAR(500) NOT NULL,
    description TEXT,
    category_id VARCHAR(50),
    difficulty VARCHAR(50),
    article_summary TEXT,
    total_questions INTEGER NOT NULL,
    time_limit_minutes INTEGER NOT NULL,
    points INTEGER NOT NULL,
    is_featured BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    is_public BOOLEAN DEFAULT true,
    tags TEXT[] DEFAULT '{}'::text[],
    thumbnail_url VARCHAR(500),
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (difficulty) REFERENCES difficulty_levels(id),
    PRIMARY KEY (id)
);
CREATE TABLE user_achievements (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    achievement_id UUID,
    unlocked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    points_awarded INTEGER DEFAULT 0,
    is_test_data BOOLEAN DEFAULT false,
    FOREIGN KEY (achievement_id) REFERENCES achievements(id) ON DELETE CASCADE,
    PRIMARY KEY (id),
    UNIQUE (user_id, achievement_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE user_category_performance (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    category_id VARCHAR(100) NOT NULL,
    category_name VARCHAR(255) NOT NULL,
    total_points INTEGER DEFAULT 0,
    quizzes_completed INTEGER DEFAULT 0,
    average_score DECIMAL DEFAULT 0.0,
    best_score DECIMAL DEFAULT 0.0,
    last_attempt_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    UNIQUE (user_id, category_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE user_preferences (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    selected_categories TEXT[],
    difficulty_preference VARCHAR(50),
    notifications_enabled BOOLEAN DEFAULT true,
    notification_frequency VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    profile_visibility BOOLEAN DEFAULT true,
    show_online_status BOOLEAN DEFAULT true,
    allow_friend_requests BOOLEAN DEFAULT true,
    share_activity_status BOOLEAN DEFAULT true,
    notification_types JSONB DEFAULT '{"challenges": true, "achievements": true, "quiz_reminders": true, "friend_activity": true, "leaderboard_updates": false, "system_announcements": true}'::jsonb,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    onboarding_completed_at TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    UNIQUE (user_id),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE user_quiz_favorites (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    quiz_id UUID,
    favorited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (user_id, quiz_id)
);
CREATE TABLE user_rank_history (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    user_id UUID,
    period_type VARCHAR(20) NOT NULL,
    old_rank INTEGER,
    new_rank INTEGER NOT NULL,
    rank_change INTEGER NOT NULL DEFAULT 0,
    points_at_change INTEGER NOT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE users (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    level VARCHAR(50) DEFAULT 'Beginner'::character varying,
    total_points INTEGER DEFAULT 0,
    current_streak INTEGER DEFAULT 0,
    best_streak INTEGER DEFAULT 0,
    total_quizzes_completed INTEGER DEFAULT 0,
    average_score DECIMAL DEFAULT 0.0,
    is_online BOOLEAN DEFAULT false,
    last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    avatar_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_test_data BOOLEAN DEFAULT false,
    auth_method VARCHAR(20) NOT NULL DEFAULT 'jwt'::character varying,
    supabase_id UUID,
    last_auth_method VARCHAR(20) NOT NULL DEFAULT 'jwt'::character varying,
    migrated_at TIMESTAMP,
    CHECK (((auth_method)::text = ANY ((ARRAY['jwt'::character varying, 'supabase'::character varying])::text[]))),
    UNIQUE (email),
    CHECK (((last_auth_method)::text = ANY ((ARRAY['jwt'::character varying, 'supabase'::character varying])::text[]))),
    PRIMARY KEY (id)
);
-- Indexes
CREATE INDEX idx_achievements_is_test_data ON public.achievements USING btree (is_test_data);
CREATE INDEX idx_app_settings_key ON public.app_settings USING btree (key);
CREATE INDEX idx_categories_name ON public.categories USING btree (name);
CREATE INDEX idx_challenges_challenged_id ON public.challenges USING btree (challengee_id);
CREATE INDEX idx_challenges_challengee_attempt_id ON public.challenges USING btree (challengee_attempt_id);
CREATE INDEX idx_challenges_challenger_attempt_id ON public.challenges USING btree (challenger_attempt_id);
CREATE INDEX idx_challenges_challenger_id ON public.challenges USING btree (challenger_id);
CREATE INDEX idx_challenges_created_at ON public.challenges USING btree (created_at);
CREATE INDEX idx_challenges_expires_at ON public.challenges USING btree (expires_at);
CREATE INDEX idx_challenges_is_test_data ON public.challenges USING btree (is_test_data);
CREATE INDEX idx_challenges_quiz_id ON public.challenges USING btree (quiz_id);
CREATE INDEX idx_challenges_status ON public.challenges USING btree (status);
CREATE INDEX idx_difficulty_levels_name ON public.difficulty_levels USING btree (name);
CREATE INDEX idx_discussion_likes_discussion_id ON public.discussion_likes USING btree (discussion_id);
CREATE INDEX idx_discussion_likes_user_id ON public.discussion_likes USING btree (user_id);
CREATE INDEX idx_discussion_replies_created_at ON public.discussion_replies USING btree (created_at);
CREATE INDEX idx_discussion_replies_discussion_id ON public.discussion_replies USING btree (discussion_id);
CREATE INDEX idx_discussion_replies_user_id ON public.discussion_replies USING btree (user_id);
CREATE INDEX idx_discussion_reply_likes_reply_id ON public.discussion_reply_likes USING btree (reply_id);
CREATE INDEX idx_discussion_reply_likes_user_id ON public.discussion_reply_likes USING btree (user_id);
CREATE INDEX idx_discussions_created_at ON public.discussions USING btree (created_at);
CREATE INDEX idx_discussions_is_test_data ON public.discussions USING btree (is_test_data);
CREATE INDEX idx_discussions_question_id ON public.discussions USING btree (question_id);
CREATE INDEX idx_discussions_quiz_id ON public.discussions USING btree (quiz_id);
CREATE INDEX idx_discussions_user_id ON public.discussions USING btree (user_id);
CREATE INDEX idx_friend_requests_created_at ON public.friend_requests USING btree (created_at);
CREATE INDEX idx_friend_requests_requested_id ON public.friend_requests USING btree (requested_id);
CREATE INDEX idx_friend_requests_requester_id ON public.friend_requests USING btree (requester_id);
CREATE INDEX idx_friend_requests_status ON public.friend_requests USING btree (status);
CREATE INDEX idx_friendships_created_at ON public.friendships USING btree (created_at);
CREATE INDEX idx_friendships_user1_id ON public.friendships USING btree (user1_id);
CREATE INDEX idx_friendships_user2_id ON public.friendships USING btree (user2_id);
CREATE INDEX idx_leaderboard_snapshots_date_period ON public.leaderboard_snapshots USING btree (snapshot_date, period_type);
CREATE INDEX idx_leaderboard_snapshots_rank ON public.leaderboard_snapshots USING btree (rank_position);
CREATE INDEX idx_leaderboard_snapshots_user_id ON public.leaderboard_snapshots USING btree (user_id);
CREATE INDEX idx_notification_frequencies_name ON public.notification_frequencies USING btree (name);
CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at);
CREATE INDEX idx_notifications_deleted_at ON public.notifications USING btree (deleted_at);
CREATE INDEX idx_notifications_is_deleted ON public.notifications USING btree (is_deleted);
CREATE INDEX idx_notifications_is_read ON public.notifications USING btree (is_read);
CREATE INDEX idx_notifications_is_test_data ON public.notifications USING btree (is_test_data);
CREATE INDEX idx_notifications_related_entity ON public.notifications USING btree (related_entity_id, related_entity_type);
CREATE INDEX idx_notifications_related_user_id ON public.notifications USING btree (related_user_id);
CREATE INDEX idx_notifications_type ON public.notifications USING btree (type);
CREATE INDEX idx_notifications_user_id ON public.notifications USING btree (user_id);
CREATE INDEX idx_notifications_user_id_is_deleted ON public.notifications USING btree (user_id, is_deleted);
CREATE INDEX idx_questions_is_test_data ON public.questions USING btree (is_test_data);
CREATE INDEX idx_questions_order_index ON public.questions USING btree (order_index);
CREATE INDEX idx_questions_question_type ON public.questions USING btree (question_type);
CREATE INDEX idx_questions_quiz_id ON public.questions USING btree (quiz_id);
CREATE INDEX idx_quiz_attempts_challenge_id ON public.quiz_attempts USING btree (challenge_id);
CREATE INDEX idx_quiz_attempts_completed_at ON public.quiz_attempts USING btree (completed_at);
CREATE INDEX idx_quiz_attempts_is_completed ON public.quiz_attempts USING btree (is_completed);
CREATE INDEX idx_quiz_attempts_is_test_data ON public.quiz_attempts USING btree (is_test_data);
CREATE INDEX idx_quiz_attempts_passed ON public.quiz_attempts USING btree (passed);
CREATE INDEX idx_quiz_attempts_quiz_id ON public.quiz_attempts USING btree (quiz_id);
CREATE INDEX idx_quiz_attempts_started_at ON public.quiz_attempts USING btree (started_at);
CREATE INDEX idx_quiz_attempts_status ON public.quiz_attempts USING btree (status);
CREATE INDEX idx_quiz_attempts_user_id ON public.quiz_attempts USING btree (user_id);
CREATE UNIQUE INDEX idx_quiz_attempts_user_quiz_active ON public.quiz_attempts USING btree (user_id, quiz_id) WHERE (is_completed = false);
CREATE INDEX idx_quiz_ratings_created_at ON public.quiz_ratings USING btree (created_at);
CREATE INDEX idx_quiz_ratings_quiz_id ON public.quiz_ratings USING btree (quiz_id);
CREATE INDEX idx_quiz_ratings_rating ON public.quiz_ratings USING btree (rating);
CREATE INDEX idx_quiz_ratings_user_id ON public.quiz_ratings USING btree (user_id);
CREATE INDEX idx_quiz_sessions_attempt_id ON public.quiz_sessions USING btree (attempt_id);
CREATE INDEX idx_quiz_sessions_last_activity ON public.quiz_sessions USING btree (last_activity_at);
CREATE INDEX idx_quiz_sessions_quiz_id ON public.quiz_sessions USING btree (quiz_id);
CREATE INDEX idx_quiz_sessions_state ON public.quiz_sessions USING btree (session_state);
CREATE INDEX idx_quiz_sessions_user_active ON public.quiz_sessions USING btree (user_id, session_state) WHERE ((session_state)::text = ANY ((ARRAY['active'::character varying, 'paused'::character varying])::text[]));
CREATE INDEX idx_quiz_sessions_user_id ON public.quiz_sessions USING btree (user_id);
CREATE INDEX idx_quiz_statistics_average_score ON public.quiz_statistics USING btree (average_score);
CREATE INDEX idx_quiz_statistics_popularity_score ON public.quiz_statistics USING btree (popularity_score);
CREATE INDEX idx_quiz_statistics_total_attempts ON public.quiz_statistics USING btree (total_attempts);
CREATE INDEX idx_quizzes_category_id ON public.quizzes USING btree (category_id);
CREATE INDEX idx_quizzes_created_at ON public.quizzes USING btree (created_at);
CREATE INDEX idx_quizzes_created_by ON public.quizzes USING btree (created_by);
CREATE INDEX idx_quizzes_difficulty ON public.quizzes USING btree (difficulty);
CREATE INDEX idx_quizzes_is_active ON public.quizzes USING btree (is_active);
CREATE INDEX idx_quizzes_is_featured ON public.quizzes USING btree (is_featured);
CREATE INDEX idx_quizzes_is_public ON public.quizzes USING btree (is_public);
CREATE INDEX idx_quizzes_is_test_data ON public.quizzes USING btree (is_test_data);
CREATE INDEX idx_quizzes_thumbnail_url ON public.quizzes USING btree (thumbnail_url);
CREATE INDEX idx_user_achievements_achievement_id ON public.user_achievements USING btree (achievement_id);
CREATE INDEX idx_user_achievements_unlocked_at ON public.user_achievements USING btree (unlocked_at);
CREATE INDEX idx_user_achievements_user_id ON public.user_achievements USING btree (user_id);
CREATE INDEX idx_user_category_performance_category_id ON public.user_category_performance USING btree (category_id);
CREATE INDEX idx_user_category_performance_total_points ON public.user_category_performance USING btree (total_points DESC);
CREATE INDEX idx_user_category_performance_user_id ON public.user_category_performance USING btree (user_id);
CREATE INDEX idx_user_preferences_onboarding_completed ON public.user_preferences USING btree (onboarding_completed_at);
CREATE INDEX idx_user_preferences_onboarding_pending ON public.user_preferences USING btree (user_id) WHERE (onboarding_completed_at IS NULL);
CREATE INDEX idx_user_preferences_updated_at ON public.user_preferences USING btree (updated_at);
CREATE INDEX idx_user_preferences_user_id ON public.user_preferences USING btree (user_id);
CREATE INDEX idx_user_quiz_favorites_favorited_at ON public.user_quiz_favorites USING btree (favorited_at);
CREATE INDEX idx_user_quiz_favorites_quiz_id ON public.user_quiz_favorites USING btree (quiz_id);
CREATE INDEX idx_user_quiz_favorites_user_id ON public.user_quiz_favorites USING btree (user_id);
CREATE INDEX idx_user_rank_history_changed_at ON public.user_rank_history USING btree (changed_at);
CREATE INDEX idx_user_rank_history_period ON public.user_rank_history USING btree (period_type);
CREATE INDEX idx_user_rank_history_user_id ON public.user_rank_history USING btree (user_id);
CREATE INDEX idx_users_auth_method ON public.users USING btree (auth_method);
CREATE INDEX idx_users_average_score ON public.users USING btree (average_score DESC);
CREATE INDEX idx_users_current_streak ON public.users USING btree (current_streak DESC);
CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_is_online ON public.users USING btree (is_online);
CREATE INDEX idx_users_is_test_data ON public.users USING btree (is_test_data);
CREATE INDEX idx_users_last_active ON public.users USING btree (last_active);
CREATE INDEX idx_users_last_auth_method ON public.users USING btree (last_auth_method);
CREATE INDEX idx_users_level ON public.users USING btree (level);
CREATE INDEX idx_users_migrated_at ON public.users USING btree (migrated_at);
CREATE INDEX idx_users_supabase_id ON public.users USING btree (supabase_id);
CREATE UNIQUE INDEX idx_users_supabase_id_unique ON public.users USING btree (supabase_id) WHERE (supabase_id IS NOT NULL);
CREATE INDEX idx_users_total_points ON public.users USING btree (total_points DESC);
CREATE INDEX idx_users_total_quizzes_completed ON public.users USING btree (total_quizzes_completed DESC);
-- Triggers
CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length();
CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();
CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();
CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger();
CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger();
CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();
CREATE TRIGGER tr_check_filters BEFORE INSERT OR UPDATE ON realtime.subscription FOR EACH ROW EXECUTE FUNCTION realtime.subscription_check_filters();
CREATE TRIGGER trigger_cleanup_friendship_on_status_change BEFORE DELETE OR UPDATE ON public.friend_requests FOR EACH ROW EXECUTE FUNCTION cleanup_friendship_on_status_change();
CREATE TRIGGER trigger_create_challenge_notification AFTER INSERT OR UPDATE ON public.challenges FOR EACH ROW EXECUTE FUNCTION create_challenge_notification();
CREATE TRIGGER trigger_create_friend_request_notification AFTER INSERT ON public.friend_requests FOR EACH ROW EXECUTE FUNCTION create_friend_request_notification();
CREATE TRIGGER trigger_create_friendship_on_accept BEFORE UPDATE ON public.friend_requests FOR EACH ROW EXECUTE FUNCTION create_friendship_on_accept();
CREATE TRIGGER trigger_update_challenges_updated_at BEFORE UPDATE ON public.challenges FOR EACH ROW EXECUTE FUNCTION update_challenges_updated_at();
CREATE TRIGGER trigger_update_last_active_on_auth BEFORE UPDATE OF last_auth_method ON public.users FOR EACH ROW EXECUTE FUNCTION update_last_active_on_auth();
CREATE TRIGGER trigger_update_user_preferences_updated_at BEFORE UPDATE ON public.user_preferences FOR EACH ROW EXECUTE FUNCTION update_user_preferences_updated_at();
CREATE TRIGGER update_achievements_updated_at BEFORE UPDATE ON public.achievements FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_app_settings_updated_at BEFORE UPDATE ON public.app_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_difficulty_levels_updated_at BEFORE UPDATE ON public.difficulty_levels FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_discussion_replies_updated_at BEFORE UPDATE ON public.discussion_replies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_discussions_updated_at BEFORE UPDATE ON public.discussions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_interests_updated_at BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_notification_frequencies_updated_at BEFORE UPDATE ON public.notification_frequencies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column();
CREATE TRIGGER update_quiz_attempts_updated_at BEFORE UPDATE ON public.quiz_attempts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_quiz_session_activity_trigger BEFORE UPDATE ON public.quiz_sessions FOR EACH ROW EXECUTE FUNCTION update_quiz_session_activity();
CREATE TRIGGER update_quiz_sessions_updated_at BEFORE UPDATE ON public.quiz_sessions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_quiz_statistics_last_updated BEFORE UPDATE ON public.quiz_statistics FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_quizzes_updated_at BEFORE UPDATE ON public.quizzes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_user_category_performance_updated_at BEFORE UPDATE ON public.user_category_performance FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_users_level_on_points_change BEFORE UPDATE OF total_points ON public.users FOR EACH ROW WHEN ((old.total_points IS DISTINCT FROM new.total_points)) EXECUTE FUNCTION update_user_level();
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
-- Row Level Security (RLS) Status
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.difficulty_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussion_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussion_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussion_reply_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friend_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_frequencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_statistics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_category_performance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_quiz_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_rank_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
-- Views
CREATE OR REPLACE VIEW public.auth_method_stats AS  SELECT auth_method,
    count(*) AS user_count,
    count(
        CASE
            WHEN (migrated_at IS NOT NULL) THEN 1
            ELSE NULL::integer
        END) AS migrated_count,
    min(created_at) AS first_user_created,
    max(last_active) AS last_activity
   FROM users
  GROUP BY auth_method;
