package database

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// GenerateSchemaSQL generates a schema.sql file from the current database state
func GenerateSchemaSQL(db *sql.DB, outputPath string) error {
	var schema strings.Builder

	// Header
	schema.WriteString("-- Database Schema for QuizNinja API\n")
	schema.WriteString(fmt.Sprintf("-- Generated automatically on: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	schema.WriteString("-- DO NOT EDIT THIS FILE MANUALLY - IT WILL BE OVERWRITTEN\n")
	schema.WriteString("-- Use migrations to modify the database schema\n\n")

	// Extensions
	extensions, err := getExtensions(db)
	if err != nil {
		return fmt.Errorf("failed to get extensions: %w", err)
	}
	if len(extensions) > 0 {
		schema.WriteString("-- Extensions\n")
		for _, ext := range extensions {
			schema.WriteString(fmt.Sprintf("CREATE EXTENSION IF NOT EXISTS \"%s\";\n", ext))
		}
		schema.WriteString("\n")
	}

	// Functions (need to be created before tables that might use them in triggers)
	functions, err := getFunctions(db)
	if err != nil {
		return fmt.Errorf("failed to get functions: %w", err)
	}
	if len(functions) > 0 {
		schema.WriteString("-- Functions\n")
		for _, function := range functions {
			schema.WriteString(function)
			schema.WriteString("\n\n")
		}
	}

	// Tables
	tables, err := getTables(db)
	if err != nil {
		return fmt.Errorf("failed to get tables: %w", err)
	}

	if len(tables) > 0 {
		schema.WriteString("-- Tables\n")
		for _, table := range tables {
			schema.WriteString(table)
			schema.WriteString("\n")
		}
	}

	// Indexes
	indexes, err := getIndexes(db)
	if err != nil {
		return fmt.Errorf("failed to get indexes: %w", err)
	}
	if len(indexes) > 0 {
		schema.WriteString("-- Indexes\n")
		for _, index := range indexes {
			schema.WriteString(index)
			schema.WriteString("\n")
		}
	}

	// Triggers
	triggers, err := getTriggers(db)
	if err != nil {
		return fmt.Errorf("failed to get triggers: %w", err)
	}
	if len(triggers) > 0 {
		schema.WriteString("-- Triggers\n")
		for _, trigger := range triggers {
			schema.WriteString(trigger)
			schema.WriteString("\n")
		}
	}

	// RLS Status
	rlsStatus, err := getRLSStatus(db)
	if err != nil {
		return fmt.Errorf("failed to get RLS status: %w", err)
	}
	if len(rlsStatus) > 0 {
		schema.WriteString("-- Row Level Security (RLS) Status\n")
		for _, rls := range rlsStatus {
			schema.WriteString(rls)
			schema.WriteString("\n")
		}
	}

	// Views
	views, err := getViews(db)
	if err != nil {
		return fmt.Errorf("failed to get views: %w", err)
	}
	if len(views) > 0 {
		schema.WriteString("-- Views\n")
		for _, view := range views {
			schema.WriteString(view)
			schema.WriteString("\n")
		}
	}

	// Write to file
	return os.WriteFile(outputPath, []byte(schema.String()), 0644)
}

// getExtensions retrieves all installed extensions
func getExtensions(db *sql.DB) ([]string, error) {
	query := `
		SELECT extname
		FROM pg_extension
		WHERE extname != 'plpgsql'
		ORDER BY extname;
	`

	rows, err := db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var extensions []string
	for rows.Next() {
		var ext string
		if err := rows.Scan(&ext); err != nil {
			return nil, err
		}
		extensions = append(extensions, ext)
	}

	return extensions, nil
}

// getFunctions retrieves all user-defined functions
func getFunctions(db *sql.DB) ([]string, error) {
	query := `
		SELECT
			pg_get_functiondef(p.oid) || ';'
		FROM pg_proc p
		LEFT JOIN pg_namespace n ON p.pronamespace = n.oid
		WHERE n.nspname = 'public'
		AND p.prokind = 'f'
		ORDER BY p.proname;
	`

	rows, err := db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var functions []string
	for rows.Next() {
		var function string
		if err := rows.Scan(&function); err != nil {
			return nil, err
		}
		functions = append(functions, function)
	}

	return functions, nil
}

// getTables retrieves all table definitions
func getTables(db *sql.DB) ([]string, error) {
	// Get all table names first
	tableQuery := `
		SELECT tablename
		FROM pg_tables
		WHERE schemaname = 'public'
		AND tablename != 'migrations'
		ORDER BY tablename;
	`

	rows, err := db.Query(tableQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var tableNames []string
	for rows.Next() {
		var tableName string
		if err := rows.Scan(&tableName); err != nil {
			return nil, err
		}
		tableNames = append(tableNames, tableName)
	}

	var tables []string
	for _, tableName := range tableNames {
		tableDef, err := getTableDefinition(db, tableName)
		if err != nil {
			return nil, fmt.Errorf("failed to get definition for table %s: %w", tableName, err)
		}
		tables = append(tables, tableDef)
	}

	return tables, nil
}

// getTableDefinition generates CREATE TABLE statement for a specific table
func getTableDefinition(db *sql.DB, tableName string) (string, error) {
	var def strings.Builder
	def.WriteString(fmt.Sprintf("CREATE TABLE %s (\n", tableName))

	// Get columns
	columnQuery := `
		SELECT
			column_name,
			data_type,
			character_maximum_length,
			is_nullable,
			column_default,
			udt_name
		FROM information_schema.columns
		WHERE table_name = $1
		AND table_schema = 'public'
		ORDER BY ordinal_position;
	`

	rows, err := db.Query(columnQuery, tableName)
	if err != nil {
		return "", err
	}
	defer rows.Close()

	var columns []string
	for rows.Next() {
		var colName, dataType, udtName string
		var maxLength sql.NullInt64
		var isNullable, colDefault sql.NullString

		if err := rows.Scan(&colName, &dataType, &maxLength, &isNullable, &colDefault, &udtName); err != nil {
			return "", err
		}

		var colDef strings.Builder
		colDef.WriteString(fmt.Sprintf("    %s ", colName))

		// Handle data type
		switch dataType {
		case "character varying":
			if maxLength.Valid {
				colDef.WriteString(fmt.Sprintf("VARCHAR(%d)", maxLength.Int64))
			} else {
				colDef.WriteString("VARCHAR")
			}
		case "character":
			if maxLength.Valid {
				colDef.WriteString(fmt.Sprintf("CHAR(%d)", maxLength.Int64))
			} else {
				colDef.WriteString("CHAR")
			}
		case "text":
			colDef.WriteString("TEXT")
		case "integer":
			colDef.WriteString("INTEGER")
		case "bigint":
			colDef.WriteString("BIGINT")
		case "smallint":
			colDef.WriteString("SMALLINT")
		case "boolean":
			colDef.WriteString("BOOLEAN")
		case "timestamp without time zone":
			colDef.WriteString("TIMESTAMP")
		case "timestamp with time zone":
			colDef.WriteString("TIMESTAMP WITH TIME ZONE")
		case "numeric":
			colDef.WriteString("DECIMAL")
		case "uuid":
			colDef.WriteString("UUID")
		case "ARRAY":
			// Handle arrays (like TEXT[])
			if udtName == "_text" {
				colDef.WriteString("TEXT[]")
			} else {
				colDef.WriteString(strings.ToUpper(udtName))
			}
		default:
			colDef.WriteString(strings.ToUpper(dataType))
		}

		// Handle NOT NULL
		if isNullable.Valid && isNullable.String == "NO" {
			colDef.WriteString(" NOT NULL")
		}

		// Handle DEFAULT
		if colDefault.Valid && colDefault.String != "" {
			colDef.WriteString(fmt.Sprintf(" DEFAULT %s", colDefault.String))
		}

		columns = append(columns, colDef.String())
	}

	// Get constraints
	constraintQuery := `
		SELECT
			con.conname,
			con.contype,
			pg_get_constraintdef(con.oid)
		FROM pg_constraint con
		JOIN pg_class rel ON rel.oid = con.conrelid
		JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
		WHERE rel.relname = $1
		AND nsp.nspname = 'public'
		AND con.contype IN ('p', 'f', 'u', 'c')
		ORDER BY con.conname;
	`

	rows, err = db.Query(constraintQuery, tableName)
	if err != nil {
		return "", err
	}
	defer rows.Close()

	var constraints []string
	for rows.Next() {
		var conName, conType, conDef string
		if err := rows.Scan(&conName, &conType, &conDef); err != nil {
			return "", err
		}

		switch conType {
		case "p":
			constraints = append(constraints, fmt.Sprintf("    %s", conDef))
		case "f":
			constraints = append(constraints, fmt.Sprintf("    %s", conDef))
		case "u":
			constraints = append(constraints, fmt.Sprintf("    %s", conDef))
		case "c":
			constraints = append(constraints, fmt.Sprintf("    %s", conDef))
		}
	}

	// Combine columns and constraints
	allItems := append(columns, constraints...)
	def.WriteString(strings.Join(allItems, ",\n"))
	def.WriteString("\n);")

	return def.String(), nil
}

// getIndexes retrieves all index definitions
func getIndexes(db *sql.DB) ([]string, error) {
	query := `
		SELECT pg_get_indexdef(indexrelid) || ';'
		FROM pg_index
		JOIN pg_class ON pg_class.oid = pg_index.indexrelid
		JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
		WHERE pg_namespace.nspname = 'public'
		AND NOT indisprimary
		AND NOT EXISTS (
			SELECT 1 FROM pg_constraint
			WHERE conindid = pg_index.indexrelid
		)
		ORDER BY pg_class.relname;
	`

	rows, err := db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var indexes []string
	for rows.Next() {
		var index string
		if err := rows.Scan(&index); err != nil {
			return nil, err
		}
		indexes = append(indexes, index)
	}

	return indexes, nil
}

// getTriggers retrieves all trigger definitions
func getTriggers(db *sql.DB) ([]string, error) {
	query := `
		SELECT pg_get_triggerdef(oid) || ';'
		FROM pg_trigger
		WHERE NOT tgisinternal
		ORDER BY tgname;
	`

	rows, err := db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var triggers []string
	for rows.Next() {
		var trigger string
		if err := rows.Scan(&trigger); err != nil {
			return nil, err
		}
		triggers = append(triggers, trigger)
	}

	return triggers, nil
}

// getRLSStatus retrieves RLS status for all tables
func getRLSStatus(db *sql.DB) ([]string, error) {
	query := `
		SELECT
			'ALTER TABLE ' || schemaname || '.' || tablename || ' ENABLE ROW LEVEL SECURITY;' as rls_statement
		FROM pg_tables
		WHERE schemaname = 'public'
		AND tablename != 'migrations'
		AND rowsecurity = true
		ORDER BY tablename;
	`

	rows, err := db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var rlsStatements []string
	for rows.Next() {
		var stmt string
		if err := rows.Scan(&stmt); err != nil {
			return nil, err
		}
		rlsStatements = append(rlsStatements, stmt)
	}

	return rlsStatements, nil
}

// getViews retrieves all view definitions
func getViews(db *sql.DB) ([]string, error) {
	query := `
		SELECT
			'CREATE OR REPLACE VIEW ' || schemaname || '.' || viewname || ' AS ' || definition
		FROM pg_views
		WHERE schemaname = 'public'
		ORDER BY viewname;
	`

	rows, err := db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var views []string
	for rows.Next() {
		var view string
		if err := rows.Scan(&view); err != nil {
			return nil, err
		}
		views = append(views, view)
	}

	return views, nil
}

// UpdateSchemaAfterMigration should be called after running migrations
func UpdateSchemaAfterMigration(db *sql.DB) error {
	// Get the current working directory
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	// Try multiple possible paths for schema.sql
	possiblePaths := []string{
		"database/schema.sql",                     // From project root
		"../database/schema.sql",                  // From tests directory
		filepath.Join(cwd, "database/schema.sql"), // Absolute path from cwd
	}

	var schemaPath string
	for _, path := range possiblePaths {
		dir := filepath.Dir(path)
		if _, err := os.Stat(dir); err == nil {
			schemaPath = path
			break
		}
	}

	if schemaPath == "" {
		// If no valid path found, create the database directory in current location
		if err := os.MkdirAll("database", 0755); err != nil {
			return fmt.Errorf("failed to create database directory: %w", err)
		}
		schemaPath = "database/schema.sql"
	}

	return GenerateSchemaSQL(db, schemaPath)
}
